log-level: INFO
declaration-grace: 3600 # Seconds before declaration is displayed again after reconnecting
language:
    +color-code: '§'
    +console: '{0}' # 0 = Console Name
    greeting: # 1 = World Age, 2 = Server Size, 3+ = Switches
        - '-> §5==== §7Legitimate Survival (mc.rJump.com)'
        - '-> §5==== §7World Active: §b{1} §5== §7Size: §b{2}'
    declaration:  # 1 = Joining Player Display Name, 2 = Set, 3 = From Player Display Name, 4 = Text, 5 = Set Age
        - '§r-> §5§k#§5---------------------------------------------§k#'
        - '-> §5|§r {4}'
        - '-> §5|§r      §8{5} ago from {3}'
        - '§r-> §5§k#§5---------------------------------------------§k#'
    missed: '-> §c* §7You missed messages §8(§7To view: §5/doorman§8)'
    history:
        body: '-> §8{2,date,yyyy MMM dd HH:mm} {1,choice,0#§7|1#§c* §f}{4} §8<§7{3}§8>' # 1 = Missed(0|1), 2 = Set, 3 = From Player Display Name, 4 = Text, 5 = Set Age, 6 = Index
        footer: '-> §8Page §7§l{1} §8of §7{2} §8(§7To view: §5/doorman <Page>§8)' # 1 = Current Page, 2 = Total Page Count
    unknown-page: '-> §7Page §enot available§7: §f§o{1,number,#}'
    no-message: '-> §7Server join message §f§o{1,number,#} §enot configured' # 1 = Index
    requires-argument: '-> §7Required §cargument missing§7: §7§o{1}' # 1 = Argument Name
    reload: '-> §7{1} plugin §2reloaded' # 1 = Plugin Name
version: @VERSION@