log-level: INFO
declaration-grace: 3600 # Seconds before declaration is displayed again after reconnecting
switches:
greeting:
    headers: []
    arguments: []
language:
    color-code: '§'
    greeting: # 1 = World Age, 2 = Server Size, 3+ = Switches
        - '-> §5====§r §7Legitimate Survival (mc.rJump.com)'
        - '-> §5====§r §7World Active: §b{1}§r §5==§r §7Size: §b{2}§r'
    declaration:  # 1 = Joining Player Display Name, 2 = Set, 3 = From Player Display Name, 4 = Text, 5 = Set Age
        - '§r-> §5§k#§5---------------------------------------------§k#'
        - '-> §5|§r {4}'
        - '-> §5|§r      §8{5} ago from {3}'
        - '§r-> §5§k#§5---------------------------------------------§k#'
    no-history: '-> §7Declaration §ehistory not available'
    requires-argument: '-> §7Required §cargument missing§7: §7§o{1}' # 1 = Argument Name
    reload: '-> §7{1} plugin §2reloaded' # 1 = Plugin Name
version: @VERSION@